// Auto-generated mapping of static images to Supabase Storage URLs
export const SUPABASE_ASSETS: Record<string, string> = {
  "/images/article card 1.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/article-card-1.webp",
  "article card 1.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/article-card-1.webp",
  "/images/ARTICLES STORIES.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/articles-stories.webp",
  "ARTICLES STORIES.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/articles-stories.webp",
  "/images/ARTICLES STORIES2.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/articles-stories2.webp",
  "ARTICLES STORIES2.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/articles-stories2.webp",
  "/images/ARTICLES STORIES3.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/articles-stories3.webp",
  "ARTICLES STORIES3.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/articles-stories3.webp",
  "/images/ARTICLES STORIES4.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/articles-stories4.webp",
  "ARTICLES STORIES4.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/articles-stories4.webp",
  "/images/Bacground-jam1.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/background-jam1.webp",
  "Bacground-jam1.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/background-jam1.webp",
  "/images/center-cap.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/center-cap.webp",
  "center-cap.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/center-cap.webp",
  "/images/FOOTER.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/footer.webp",
  "FOOTER.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/footer.webp",
  "/images/Frame 1.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/frame-1.webp",
  "Frame 1.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/frame-1.webp",
  "/images/Group 351.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/group-351.webp",
  "Group 351.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/group-351.webp",
  "/images/Group 361.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/group-361.webp",
  "Group 361.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/group-361.webp",
  "/images/Group 37-1.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/group-37-1.webp",
  "Group 37-1.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/group-37-1.webp",
  "/images/Group 37.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/group-37.webp",
  "Group 37.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/group-37.webp",
  "/images/Group 381.jpeg": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/group-381.webp",
  "Group 381.jpeg": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/group-381.webp",
  "/images/Group 39.jpeg": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/group-39.webp",
  "Group 39.jpeg": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/group-39.webp",
  "/images/Group 42.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/group-42.webp",
  "Group 42.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/group-42.webp",
  "/images/Group 43.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/group-43.webp",
  "Group 43.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/group-43.webp",
  "/images/Group 44.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/group-44.webp",
  "Group 44.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/group-44.webp",
  "/images/Group 47.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/group-47.webp",
  "Group 47.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/group-47.webp",
  "/images/hour-hand.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/hour-hand.webp",
  "hour-hand.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/hour-hand.webp",
  "/images/ICON CHROME 1.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/icon-chrome-1.webp",
  "ICON CHROME 1.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/icon-chrome-1.webp",
  "/images/Jam FULL.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/jam-full.webp",
  "Jam FULL.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/jam-full.webp",
  "/images/Jam Mantra.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/jam-mantra.webp",
  "Jam Mantra.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/jam-mantra.webp",
  "/images/MANTRA KV FINAL 1.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/mantra-kv-final-1.webp",
  "MANTRA KV FINAL 1.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/mantra-kv-final-1.webp",
  "/images/MANTRA KV FINAL 2.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/mantra-kv-final-2.webp",
  "MANTRA KV FINAL 2.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/mantra-kv-final-2.webp",
  "/images/MANTRA-OVERSIZED T-SHIRT.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/mantra-oversized-t-shirt.webp",
  "MANTRA-OVERSIZED T-SHIRT.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/mantra-oversized-t-shirt.webp",
  "/images/Mask group.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/mask-group.webp",
  "Mask group.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/mask-group.webp",
  "/images/MASK.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/mask.webp",
  "MASK.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/mask.webp",
  "/images/minute-hand.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/minute-hand.webp",
  "minute-hand.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/minute-hand.webp",
  "/images/pexels-wendelmoretti-1925630 1.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/pexels-wendelmoretti-1925630-1.webp",
  "pexels-wendelmoretti-1925630 1.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/pexels-wendelmoretti-1925630-1.webp",
  "/images/pexels-wendelmoretti-1925630(background mata untuk jam).png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/background-mata-jam.webp",
  "pexels-wendelmoretti-1925630(background mata untuk jam).png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/background-mata-jam.webp",
  "/images/Rectangle 26.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/rectangle-26.webp",
  "Rectangle 26.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/rectangle-26.webp",
  "/images/Rectangle 28.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/rectangle-28.webp",
  "Rectangle 28.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/rectangle-28.webp",
  "/images/Rectangle 29.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/rectangle-29.webp",
  "Rectangle 29.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/rectangle-29.webp",
  "/images/Rectangle 31.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/rectangle-31.webp",
  "Rectangle 31.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/rectangle-31.webp",
  "/images/Rectangle 32.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/rectangle-32.webp",
  "Rectangle 32.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/rectangle-32.webp",
  "/images/Rectangle 33.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/rectangle-33.webp",
  "Rectangle 33.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/rectangle-33.webp",
  "/images/Rectangle 34.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/rectangle-34.webp",
  "Rectangle 34.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/rectangle-34.webp",
  "/images/Rectangle 35.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/rectangle-35.webp",
  "Rectangle 35.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/rectangle-35.webp",
  "/images/Rectangle 36.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/rectangle-36.webp",
  "Rectangle 36.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/rectangle-36.webp",
  "/images/Rectangle 37.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/rectangle-37.webp",
  "Rectangle 37.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/rectangle-37.webp",
  "/images/Rectangle 38.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/rectangle-38.webp",
  "Rectangle 38.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/rectangle-38.webp",
  "/images/vid art1.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/vid-art1.webp",
  "vid art1.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/vid-art1.webp",
  "/images/WORDMARK CHROME 1.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/wordmark-chrome-1.webp",
  "WORDMARK CHROME 1.png": "https://xcorxezfhjmncyxegrvi.supabase.co/storage/v1/object/public/site-assets/wordmark-chrome-1.webp"
};

export function getAssetUrl(pathOrName: string, fallback = "/images/placeholder.jpg"): string {
  if (!pathOrName) return fallback;
  if (pathOrName.startsWith("http://") || pathOrName.startsWith("https://")) {
    return pathOrName;
  }
  return SUPABASE_ASSETS[pathOrName] || SUPABASE_ASSETS[`/images/${pathOrName.replace(/^\//, "")}`] || pathOrName;
}
